#!/bin/bash
puppet resource package git ensure=present
puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=running
puppet resource file /testdir/clone ensure=absent force=true
puppet resource file /testdir ensure=directory
puppet resource file /testdir/clone ensure=directory
cd /testdir/clone
git clone https://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@github.com/22053351_repo/22053351_repo.git
cp -p /testdir/clone/22053351_repo/index.html /var/www/html

